### PR TITLE
Choose for sequences via maybe or either

### PR DESCRIPTION
**Pull request by atifaziz**
This PR proposes adding an extension for sequence similar to [`Seq.choose`](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/seq.choose%5B't,'u%5D-function-%5Bfsharp%5D) in F#.

### CODE REVIEW

**Comment by atifaziz** [comment]
@nlkl Any problems with this PR?

**Comment by nlkl** [comment]
Hi @atifaziz 

Thank you for the PR - and sorry for the late reply!

I am a bit split about this PR. On one side, I can see the convenience in building up a library of such utility collection functionality, but on the other hand I think it might be a bit too specific for Optional itself.

In general,  I try to keep Optional reasonably focused around its core functionality. In order to make it actually _usable_ though, Optional also provides various surrounding features such as basic collection interop and utility functions.

I think this PR diverges a bit from the core ideas, as it is actually new collection functionality (from a C# perspective), and not simply interop/convenience. It is of course a minor addition, but I fear it might be a slippery slope.

Finally, I am not sure I think the added value outweighs the above mentioned costs. Consider the following:

```csharp
var jobs = people.Select(GetCurrentJob).Values();

// VS

var jobs = people.Choose(GetCurrentJob);
```

The difference is minor, so unless there is something I am missing, I am not sure I can justify merging the PR.

Any thoughts?

Best regards,
/Nils

**Comment by atifaziz** [comment]
The way [`Values()` is implemented](https://github.com/nlkl/Optional/blob/6360b071a73109ffbb453c9391f6bae0edcfe1f0/src/Optional/Collections/OptionCollectionExtensions.cs#L21), it ends up causing an allocation for every option so it's not about just looks. Rather, the benefits or devil is in the detail.

**Comment by nlkl** [comment]
Hi again,

The proposed implementation simply peforms the Select+Values chaining inside the Choose method, so it is hardly going to cause fewer allocations than simply calling it directly. Is there something I am missing?

Even so, I recognize that the original implementation was a bit naive, and I have optimized this a bit on the develop branch ([link](https://github.com/nlkl/Optional/blob/develop/src/Optional/Collections/OptionCollectionExtensions.cs#L22-L28)).

/Nils

**Comment by atifaziz** [comment]
> The proposed implementation simply peforms the Select+Values chaining inside the Choose method, so it is hardly going to cause fewer allocations than simply calling it directly. Is there something I am missing?

No, I was missing it. Looks like [my initial merge with master](https://github.com/nlkl/Optional/pull/37/commits/c9a2cd5dc5150c969afebf4ad64fd06ec07d20fa) didn't account for `Flatten` having been renamed to `Values` and I could have sworn I was reading two different implementations. I have a feeling that R# took me to [the only remaining definition(s)  `in OptionExtensions`](https://github.com/nlkl/Optional/blob/eb98dd2644f59c755ff23e19f57359466a52cc60/src/Optional/OptionExtensions.cs#L201-L217).

I understand you're split on the topic of adding this and wary of a slippery slope/scope. It's a one-liner extension that I can add to my projects locally so I'm not going to be spend too much energy arguing its merits. It just seemed natural to contribute it to Optional with unit tests.

**Pull request closed without merging**
